config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :restaurants do
    collection do
      get :top
    end
    member do
      get :chef
    end
    resources :reviews, only: [:new, :create]
  end
resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :chef]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  def top
    @restaurants = Restaurant.where(stars: 5)
  end

  def chef
    @chef_name = @restaurant.chef_name
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :chef_name, :address, :stars)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, except: [:destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container mt-3">
      <%= yield %>
  </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do | f | %>
<%= f.input :name %>
<%= f.input :chef_name %>
<%= f.input :address %>
<%= f.input :stars %>
<%= f.submit class:"btn btn-primary btn-sm" %>
<% end %>

app/views/restaurants/chef.html.erb
<h1><%= @restaurant.name %>'s Chef is <%= @chef_name %></h1>

<%= link_to "Back", restaurant_path(@restaurant) %>
<br/>
<%= link_to "Home", restaurants_path %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render "form" %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<%= link_to "Create new Restaurant", new_restaurant_path %>
<br/>
<%= link_to "Top 5⭐ Restaurants", top_restaurants_path %>
<br/>
<br/>

<ul>
    <% @restaurants.each do |restaurant| %>
  <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
      <%= restaurant.address %>
      <%= "⭐" * restaurant.stars %>
    <% end %>
  </li>
</ul>

app/views/restaurants/new.html.erb
<h1>Create new Restaurant</h1>

<%= render "form" %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<ul>
  <li>
    <%= link_to "Chef", chef_restaurant_path(@restaurant) %>
  </li>
  <li>
    <strong>Address: </strong><%= @restaurant.address %>
  </li>
  <li>
    <strong>Rating: </strong><%= "⭐" * @restaurant.stars %>
  </li>
    <li>
    <strong>Reviews:</strong>
      <ul class="list-group">
       <% @restaurant.reviews.each do |review| %>
        <li class="list-group-item">
          <%= review.content %>
          <%= link_to "Delete review", review_path(review), method: :delete,
            data: { confirm: "Are you sure?" }  %>
        </li>
        <% end %>
      </ul>
  </li>
</ul>

<%= link_to "Add Review", new_restaurant_review_path(@restaurant) %>
<br/>
<%= link_to "Edit Restaurant", edit_restaurant_path(@restaurant) %>
<br/>
<%= link_to "Delete Restaurant", restaurant_path(@restaurant),method: :delete,
            data: { confirm: "Are you sure?" }  %>
<br/><br/>
<%= link_to "Home", restaurants_path %>

app/views/restaurants/top.html.erb
<h1>Top 5⭐ Restaurants</h1>

<ul>
    <% @restaurants.each do |restaurant| %>
  <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
      <%= restaurant.address %>
      <%= "⭐" * restaurant.stars %>
    <% end %>
  </li>
</ul>

<br/>
<%= link_to "Home", restaurants_path %>

app/views/reviews/new.html.erb
<h1>Create Review for <%= @restaurant.name %></h1>

<%= simple_form_for [ @restaurant, @review ] do | f | %>
  <%= f.input :content %>
  <%= f.submit class:"btn btn-primary btn-sm" %>
<% end %>